### ISSUE TITLE
The figshare link to download the DEMO data and use it

### ISSUE THREAD

**Issue by ranjanmaji** [cantinilab/scconfluence#5]
"You may download a preprocessed 10X Multiome demo dataset [here](https://figshare.com/s/b0840d90e42e37fa165f)."

The link downloads RNA_ATAC_PBMC_demo.h5mu.gz
However, when I try to gunzip this file, it says: "gzip: RNA_ATAC_PBMC_demo.h5mu.gz: not in gzip format"

Without gunziping it, and using the  following code as:

# Load data into a Muon object.
mdata = md.read_h5mu("RNA_ATAC_PBMC_demo.h5mu.gz")

I get the error:
/home/rmaji/miniconda3/envs/scconfluence/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_csv from `anndata` is deprecated. Import anndata.io.read_csv instead.
  warnings.warn(msg, FutureWarning)
/home/rmaji/miniconda3/envs/scconfluence/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_excel from `anndata` is deprecated. Import anndata.io.read_excel instead.
  warnings.warn(msg, FutureWarning)
/home/rmaji/miniconda3/envs/scconfluence/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_hdf from `anndata` is deprecated. Import anndata.io.read_hdf instead.
  warnings.warn(msg, FutureWarning)
/home/rmaji/miniconda3/envs/scconfluence/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_loom from `anndata` is deprecated. Import anndata.io.read_loom instead.
  warnings.warn(msg, FutureWarning)
/home/rmaji/miniconda3/envs/scconfluence/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_mtx from `anndata` is deprecated. Import anndata.io.read_mtx instead.
  warnings.warn(msg, FutureWarning)
/home/rmaji/miniconda3/envs/scconfluence/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  warnings.warn(msg, FutureWarning)
/home/rmaji/miniconda3/envs/scconfluence/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_umi_tools from `anndata` is deprecated. Import anndata.io.read_umi_tools instead.
  warnings.warn(msg, FutureWarning)
/home/rmaji/miniconda3/envs/scconfluence/lib/python3.11/site-packages/mudata/_core/mudata.py:1531: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
  self._update_attr("var", axis=0, join_common=join_common)
/home/rmaji/miniconda3/envs/scconfluence/lib/python3.11/site-packages/mudata/_core/mudata.py:1429: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
  self._update_attr("obs", axis=1, join_common=join_common)
MuData object with n_obs × n_vars = 8000 × 145834
  obs:	'celltype', 'modality'
  2 modalities
    rna:	4000 x 15417
    atac:	4000 x 130417
      uns:	'gene_activities_names'
      obsm:	'gene_activities'
Traceback (most recent call last):
  File "/projects/amitimeseries/work/scconfluence/try_example.py", line 13, in <module>
    mdata.uns["cross_modality1+modality2"] = cdist(mdata["modality1"].obsm["cm_features"],
                                                   ~~~~~^^^^^^^^^^^^^
  File "/home/rmaji/miniconda3/envs/scconfluence/lib/python3.11/site-packages/mudata/_core/mudata.py", line 514, in __getitem__
    return self.mod[index]
           ~~~~~~~~^^^^^^^
KeyError: 'modality1'

scverse packages (like anndata muon scanpy and mudata which are dependencies of scconfluence) versions installed are:

anndata                   0.11.1
mudata                    0.3.1
scanpy                    1.10.3
muon                      0.1.6

Thank you for checking the issue.

**Comment by jules-samaran** [comment]
Hi, 
Thank you for your interest in scConfluence and for raising this issue. 

It seems this is related with the release of newer versions of anndata and/or mudata since I uploaded the data. I haven't identified yet exactly which update caused the issue but when I installed the following older versions: anndata-0.10.5 mudata-0.2.3 muon-0.1.5 scanpy-1.9.8 which I found inside the poetry.lock file, I was able to read the file without any error.

Could you try it and tell me it that works for you?
It that's the root of the problem, this means that I might have to impose an upper bound on the versions of these packages or discuss with the scverse team about this issue.

**Comment by jules-samaran** [comment]
Actually @ranjanmaji I haven't been able to reproduce your issue and it doesn't seem that either anndata or mudata are at fault. Indeed, even with the most recent anndata and mudata versions (see the output of pip list below where I have the same dependencies as you for anndata 0.11.1, mudata 0.3.1, scanpy 1.10.3, muon 0.1.6), I don't encounter any issue.

<details>
<summary>Click to see outputs</summary>

```
>>> import mudata as md
>>> md.read_h5mu("RNA_ATAC_PBMC_demo.h5mu.gz")
/Users/jsamaran/miniconda3/envs/test_issue/lib/python3.10/site-packages/mudata/_core/mudata.py:1531: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
  self._update_attr("var", axis=0, join_common=join_common)
/Users/jsamaran/miniconda3/envs/test_issue/lib/python3.10/site-packages/mudata/_core/mudata.py:1429: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
  self._update_attr("obs", axis=1, join_common=join_common)
MuData object with n_obs × n_vars = 8000 × 145834
  obs:	'celltype', 'modality'
  2 modalities
    rna:	4000 x 15417
    atac:	4000 x 130417
      uns:	'gene_activities_names'
      obsm:	'gene_activities'
>>> exit()
(test_issue) jsamaran@ML23-2005 Downloads % pip list
Package          Version
---------------- -----------
anndata          0.11.1
array_api_compat 1.9.1
contourpy        1.3.1
cycler           0.12.1
exceptiongroup   1.2.2
fonttools        4.55.0
h5py             3.12.1
joblib           1.4.2
kiwisolver       1.4.7
legacy-api-wrap  1.4
llvmlite         0.43.0
matplotlib       3.9.2
mudata           0.3.1
MultiMAP         0.0.1
muon             0.1.6
natsort          8.4.0
networkx         3.4.2
numba            0.60.0
numpy            1.26.4
packaging        24.2
pandas           2.2.3
patsy            1.0.1
pillow           11.0.0
pip              24.3.1
protobuf         5.28.3
pynndescent      0.5.13
pyparsing        3.2.0
python-dateutil  2.9.0.post0
pytz             2024.2
scanpy           1.10.3
scikit-learn     1.5.2
scikit-misc      0.1.4
scipy            1.14.1
seaborn          0.13.2
session-info     1.0.0
setuptools       75.5.0
six              1.16.0
statsmodels      0.14.4
stdlib-list      0.11.0
threadpoolctl    3.5.0
tqdm             4.67.0
tzdata           2024.2
umap-learn       0.5.7
wheel            0.45.0
```
</details>

Could you provide me with the output of your pip list?

**Comment by ranjanmaji** [comment]
Sorry, the error occurs at line :

#Compute the cross-modality distance matrix using connected features
mdata.uns["cross_modality1+modality2"] = cdist(mdata["modality1"].obsm["cm_features"],
                                               mdata["modality2"].obsm["cm_features"])

where I get the above-described error.
pip list gives:
Package                  Version
------------------------ -----------
aiohappyeyeballs         2.4.3
aiohttp                  3.11.2
aiosignal                1.3.1
anndata                  0.11.1
array_api_compat         1.9.1
attrs                    24.2.0
cached-property          1.5.2
certifi                  2024.8.30
colorama                 0.4.6
contourpy                1.3.1
cycler                   0.12.1
exceptiongroup           1.2.2
filelock                 3.16.1
fonttools                4.55.0
frozenlist               1.5.0
fsspec                   2024.10.0
geomloss                 0.2.6
get-annotations          0.1.2
h5py                     3.12.1
idna                     3.10
igraph                   0.11.6
Jinja2                   3.1.4
joblib                   1.4.2
kiwisolver               1.4.7
legacy-api-wrap          1.4
leidenalg                0.10.2
lightning-utilities      0.11.8
llvmlite                 0.43.0
MarkupSafe               3.0.2
matplotlib               3.9.2
mpmath                   1.3.0
mudata                   0.3.1
multidict                6.1.0
munkres                  1.1.4
muon                     0.1.6
natsort                  8.4.0
networkx                 3.4.2
numba                    0.60.0
numpy                    2.0.2
nvidia-cublas-cu12       12.4.5.8
nvidia-cuda-cupti-cu12   12.4.127
nvidia-cuda-nvrtc-cu12   12.4.127
nvidia-cuda-runtime-cu12 12.4.127
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.2.1.3
nvidia-curand-cu12       10.3.5.147
nvidia-cusolver-cu12     11.6.1.9
nvidia-cusparse-cu12     12.3.1.170
nvidia-nccl-cu12         2.21.5
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.4.127
packaging                24.2
pandas                   2.2.2
patsy                    1.0.1
pillow                   11.0.0
pip                      24.3.1
POT                      0.9.5
propcache                0.2.0
protobuf                 5.28.3
pynndescent              0.5.13
pyparsing                3.2.0
python-dateutil          2.9.0.post0
pytorch-lightning        2.4.0
pytz                     2024.2
PyYAML                   6.0.2
scanpy                   1.10.3
scikit-learn             1.5.2
scipy                    1.14.1
seaborn                  0.13.2
session-info             1.0.0
setuptools               75.5.0
six                      1.16.0
statsmodels              0.14.4
stdlib-list              0.11.0
sympy                    1.13.1
texttable                1.7.0
threadpoolctl            3.5.0
torch                    2.5.1
torchmetrics             1.6.0
tqdm                     4.67.0
triton                   3.1.0
typing_extensions        4.12.2
tzdata                   2024.2
umap-learn               0.5.7
unicodedata2             15.1.0
wheel                    0.45.0
yarl                     1.17.2

**Comment by jules-samaran** [comment]
Oh that's my bad, I hadn't read carefully enough your traceback, your problem doesn't come from the file nor your environment then.

This example I put in the README is not really a script that you can run as is, I gave an example of how to run scConfluence and put as modality names placeholders "modality1" and "modality2" so that people would get the idea, but they should be replaced with "rna" and "atac" for you to be able to run this code. I should make this clearer in the README.

If you want a piece of code to show a simple application of scConfluence that you can directly run without changing anything, I would recommend looking at the [tutorials notebooks](https://scconfluence.readthedocs.io/en/latest/tutorials/RNA_ATAC_pbmc_tutorial.html).

**Comment by ranjanmaji** [comment]
Yes, I figured that out.
I was using the tutorials: "Integrating scRNA and scATAC in PBMCs". Now I get error in cell 8 with the ln: `mu.atac.pp.tfidf(mdata["atac"], log_tf=True, log_idf=True)` and the error is

MuData object with n_obs × n_vars = 8000 × 145834
  obs:  'celltype', 'modality'
  2 modalities
    rna:        4000 x 15417
    atac:       4000 x 130417
      uns:      'gene_activities_names'
      obsm:     'gene_activities'
/home/rmaji/miniconda3/envs/scconfluence/lib/python3.11/site-packages/mudata/_core/mudata.py:1531: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
  self._update_attr("var", axis=0, join_common=join_common)
/home/rmaji/miniconda3/envs/scconfluence/lib/python3.11/site-packages/mudata/_core/mudata.py:1429: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
  self._update_attr("obs", axis=1, join_common=join_common)
-------------------------
MuData object with n_obs × n_vars = 8000 × 142375
  obs:  'celltype', 'modality'
  var:  'n_cells'
  2 modalities
    rna:        4000 x 15145
      obs:      'n_genes'
      var:      'n_cells'
    atac:       4000 x 127230
      obs:      'n_genes'
      var:      'n_cells'
      uns:      'gene_activities_names'
      obsm:     'gene_activities'
Traceback (most recent call last):
  File "/projects/amitimeseries/work/scconfluence/try_example.py", line 77, in <module>
    mu.atac.pp.tfidf(mdata["atac"], log_tf=True, log_idf=True)
  File "/home/rmaji/miniconda3/envs/scconfluence/lib/python3.11/site-packages/muon/_atac/preproc.py", line 119, in tfidf
    res = np.nan_to_num(tf_idf, 0)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmaji/miniconda3/envs/scconfluence/lib/python3.11/site-packages/numpy/lib/_type_check_impl.py", line 460, in nan_to_num
    x = _nx.array(x, subok=True, copy=copy)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.

--------------------------------------------------------------------------------------------------

**Comment by ranjanmaji** [comment]
when running in the jupyter notebook, I get this more detailed error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[17], line 2
      1 import muon as mu
----> 2 mu.atac.pp.tfidf(mdata["atac"], log_tf=True, log_idf=True)
      3 sc.tl.pca(mdata["atac"], n_comps=100, zero_center=None)

File [~/miniconda3/envs/scconfluence/lib/python3.11/site-packages/muon/_atac/preproc.py:119](http://localhost:9035/lab/tree/projects/amitimeseries/work/scconfluence/~/miniconda3/envs/scconfluence/lib/python3.11/site-packages/muon/_atac/preproc.py#line=118), in tfidf(data, log_tf, log_idf, log_tfidf, scale_factor, inplace, copy, from_layer, to_layer)
    116 if log_tfidf:
    117     tf_idf = np.log1p(tf_idf)
--> 119 res = np.nan_to_num(tf_idf, 0)
    120 if not inplace:
    121     return res

File [~/miniconda3/envs/scconfluence/lib/python3.11/site-packages/numpy/lib/_type_check_impl.py:460](http://localhost:9035/lab/tree/projects/amitimeseries/work/scconfluence/~/miniconda3/envs/scconfluence/lib/python3.11/site-packages/numpy/lib/_type_check_impl.py#line=459), in nan_to_num(x, copy, nan, posinf, neginf)
    366 @array_function_dispatch(_nan_to_num_dispatcher)
    367 def nan_to_num(x, copy=True, nan=0.0, posinf=None, neginf=None):
    368     """
    369     Replace NaN with zero and infinity with large finite numbers (default
    370     behaviour) or with the numbers defined by the user using the `nan`,
   (...)
    458     array([222222.+111111.j, 111111.     +0.j, 111111.+222222.j])
    459     """
--> 460     x = _nx.array(x, subok=True, copy=copy)
    461     xtype = x.dtype.type
    463     isscalar = (x.ndim == 0)

ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.

**Comment by jules-samaran** [comment]
I don't obtain this error which is probably due to an incompatibility between your muon and numpy versions. 
What's weird is that in the environment you've shown me I don't even see scconfluence installed and you have numpy 2.0 which is not allowed yet (I'll update soon the allowed versions but it's not done yet) for scconfluence. 
Are you sure you've installed scConfluence ? You should have numpy 1.26.4 if it were the case

**Comment by ranjanmaji** [comment]
Hi there, After removing the numpy 2.0, and replacing with numpy 1.26.4. , I got no errors. I will check again and update you.

**Comment by ranjanmaji** [comment]
Yes, this time no error in any line. Except for a few warnings. like WARNING: adata.X seems to be already log-transformed.
